FROM python:3.13

# Creamos un directorio para la aplicacion
WORKDIR /app

# Copiamos la aplicacion..
COPY . .

# Instalamos las dependencias
# RUN pip install -r requirements.txt
# Exponemos un puerto

# EXPOSE 2020

# Iniciamos la aplicacion
CMD ["python", "app.py"]